### PR TITLE
Changed link to French data and adjusted handling of cases (replacing "," with ".")

### PR DESCRIPTION
**Pull request by kaitejohnson**
Let me know if this makes sense Stephen! I don't know French so this was mostly an educated guess that the data looks right!

### CODE REVIEW

**Comment by kaitejohnson** [comment]
@sjbeckett Couldn't figure out how to assign you as reviewer

**Comment by kaitejohnson** [comment]
Alternatively, you can just copy the few lines of code that changed and reject this PR

**Comment by sjbeckett** [comment]
Ah, I was just starting to work on this too @kaitejohnson! Thanks! We identified the same dataset choice and good spot with the comma decimal system. Will want to doublecheck tomorrow that the URL is stable to updates. Will copy your edits over to avoid adding the additional files.

We will have to find a time to discuss the timeseries project!

(Note the metadata description for datasets is here: https://static.data.gouv.fr/resources/donnees-de-laboratoires-pour-le-depistage-a-compter-du-18-05-2022-si-dep/20220512-153419/2022-05-12-sidep-evol-open-data.pdf )

**Comment by kaitejohnson** [comment]
Great!

And agreed-- think theres tons of potential there!

**Comment by kaitejohnson** [comment]
Oop! One more thing! I  don't know why this happens, but the P column in the dataset gets read in as a numeric automatically, where it changes a 1,00 to a 100 (when it should really be a 1.00). So the population numbers that you are using for the pInf in the current code are 100 x as large as they should be. Should just be a quick fix to either change the input type to a character, replace with a period, and then convert!

**Comment by sjbeckett** [comment]
Awesome, have made a fix!

**Comment by kaitejohnson** [comment]
@sjbeckett sorry to keep bothering you with this, but the NYT changed their data formatting, replacing us-counties.csv with annual datasets and a us-counties-recent.csv. We should replace the dataurl in LoadUS.R with 
`dataurl <- "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties-recent.csv"`

**Pull request closed without merging**
